[package]
name = "in-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
vek = "0.15.4"
pollster = "0.2.4"
# until 0.35.2 is bumped
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", features = ["raw-window-handle"] }
env_logger = "0.9.0"
wgpu = "0.12.0"

